services:
  - docker
  
script:
- git clone https://github.com/cloudflare/flan.git
- ls
- cd flan
- docker --version
- make build
- travis_wait 60 make start >> start.out
- tail -500 start.out
- travis_wait 60 make html >> html.out
- tail -500 html.out
